version: '3.8'

services:
  database:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_DB=dreamescape
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=kikibaza
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local